# docker-compose automatically read variables from .env, no need to configure
services:
  ${DOCKER_CONTAINER}:
    build: .
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    container_name: ${DOCKER_CONTAINER}
    volumes:
      # This is a bind mount, not a named volume.
      # '.' links to docker-compose.yaml's folder.
      # Create and sync 2 folders named "output" inside and outside container.
      - ./output:/app/output
