name: Run Transformations

on:
  push:
    branches:
      - main
  # Adds a button to manually select a branch and trigger workflow run.
  workflow_dispatch:

jobs:
  run-docker-and-export:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_REPO: ${{secrets.DOCKER_REPO}}
      DOCKER_CONTAINER: ${{secrets.DOCKER_CONTAINER}}
    steps:
      - name: Checkout repo to Github Actions runner
        uses: actions/checkout@v4
      - name: Pull image
        run: docker compose pull
      - name: Execute docker commands to run container and export CSV
        run:  bash run_docker.sh
      - name: Download CSV
        uses: actions/upload-artifact@v4
        with:
          # Artifact will automatically zip file so name should end in zip extension.
          # Simply clicking on file in Artifacts will download to Downloads folder.
          # To specify folder, Right+click > Save link as > choose folder to download to
          name: numpy_ai_job_datasets.zip
          path: numpy_ai_job_datasets.csv
          # No need to stress about quickly downloading file. If it expires, simply re-run the job. 
          retention-days: 1
