name: Run Transformations

on:
  push:
    branches:
      - main

jobs:
  run-docker-and-export:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_REPO: ${{secrets.DOCKER_REPO}}
      DOCKER_CONTAINER: ${{secrets.DOCKER_CONTAINER}}
    steps:
      - name: Checkout repo to Github Actions runner
        uses: actions/checkout@v4
      - name: Remove dangling images
        run: docker image prune -f
      - name: Pull image
        run: docker compose pull
      - name: Run container and remove previous versions of the same container
        run: docker compose up --remove-orphans
      - name: Download CSV
        uses: actions/upload-artifact@v4
        with:
          name: numpy_ai_job_datasets.csv
          path: output/numpy_ai_job_datasets.csv
          # No need to stress about quickly downloading CSV. If it expires, simply re-run the job. 
          retention-days: 1
